packages:
  required:
    apt:
    - apache2
    - git
    - nodejs
    - yarn
    - acl

repos:
  key_urls:
  - https://dl.yarnpkg.com/debian/pubkey.gpg

  strings:
  - "deb https://dl.yarnpkg.com/debian stable main"

apache:
  a2enmod:
    module_list:
      - rewrite
      - headers
      - ssl

security:
  app_user: ubuntu
