name: Deployment test


#Run workflow on successful merge to development
on:
  - push
  - pull_request


jobs:
  test-deployment:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        

      # Run a test deployment on the runner with ansible
      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          # Required, playbook filepath
          playbook: play.yml
          # Optional, directory where playbooks live
          directory: ./ansible
          # Optional, literal inventory file contents
          inventory: |
            [casper-mem-port-frontend]
            localhost ansible_connection=local

          # Optional, additional flags to pass to ansible-playbook
          options: |
            --limit casper-mem-port-frontend
            --verbose
            --extra_vars version=${{ GITHUB_REF }}